Restore line printing in tracer
openfisca/openfisca-core pull request #1304
Opened 2024-11-20 17:39 UTC by guillett

Thanks for contributing to OpenFisca! Remove this line, as well as any other in the following that don't fit your contribution  :)

#### Technical changes

- Fix `computation_log`.

2024-11-21 02:04 UTC, bonjourmauko commented
Hi! Was this a bug introduced recently? I'd love to add a failing test for this. If you could point me out at how to reproduce the error and the expected behaviour, I could help with the test.

2024-11-21 04:45 UTC, bonjourmauko commented
Ok I understood now: printing/logging has nothing to do in the computation log, which is just a log accumulator —like a writer monad transformer, sort of.

In `test_runner.py`, you could either:

1. Get the log buffer and log it to stdout there.
2. Pass down a function to the tracer with how you want to print/log the log buffer.

Something like this should give you what you want:

```py
# task_runner.py
@staticmethod
def print_computation_log(tracer, aggregate, max_depth) -> None:
    buffer = tracer.computation_log.lines(aggregate, max_depth)
    for line in buffer:
        print(line)
```

Also, using `print` is making the linter fail in CI, you have to use a logger for that.

Hope it helps :)

2024-11-21 04:46 UTC, bonjourmauko requested changes
Ok I understood now: printing/logging has nothing to do in the computation log, which is just a log accumulator —like a writer monad transformer, sort of.

In `test_runner.py`, you could either:

1. Get the log buffer and log it to stdout there.
2. Pass down a function to the tracer with how you want to print/log the log buffer.

Something like this should give you what you want (just an idea):

```py
# task_runner.py
@staticmethod
def print_computation_log(tracer, aggregate, max_depth) -> None:
    buffer = tracer.computation_log.lines(aggregate, max_depth)
    for line in buffer:
        print(line)
```

Also, using `print` is making the linter fail in CI, you have to use a logger for that.

Hope it helps :)

2024-11-21 10:35 UTC, guillett commented
Thanks @bonjourmauko , I don't have much time to follow up. To me, this is a regression and I need this fix to work locally.

2024-11-21 10:51 UTC, bonjourmauko commented
@guillett If you give me the command to use I can propose you a stacked PR with the proposed fix.

Concerning `print`, even if I accept it, you won't be able to merge because of the linter.

2024-11-21 11:04 UTC, bonjourmauko commented
Oh I see the regression was introduced here https://github.com/openfisca/openfisca-core/commit/2f8072fdf270bfd204f1103b227a893f80a3bdaa#diff-fc2477fbba8037857fb9287895920ee5a1015c5eda4edb50832af14232fdd10b

2024-11-21 11:08 UTC, bonjourmauko commented on openfisca_core/tracers/computation_log.py
> +            print(line)
```suggestion
            print(line)  # noqa: T201
```

2025-03-04 04:42 UTC, benjello approved these changes

2025-03-05 16:01 UTC, benjello commented
@guillett : I modified the changlog so the linter passes but we still have a problem with a conda build.
@benoit-cty: didn't we got this error already ? Any hint ?

2025-03-06 10:01 UTC, benoit-cty commented
> @guillett : I modified the changlog so the linter passes but we still have a problem with a conda build. @benoit-cty: didn't we got this error already ? Any hint ?

Well, the error in Conda complains about Numpy : `If using `np.array(obj, copy=False)` replace it with `np.asarray(obj)` to allow a copy when needed (no behavior change in NumPy 1.x).`
Because despite the `np1.6.24` in the name of the test, it is a Numpy 2 version that has been installed:

`  + numpy                               2.2.3  py310hefbff90_0       conda-forge                   8MB `

2025-03-06 16:12 UTC, bonjourmauko commented
There is definitely a problem with the conda's config.

2025-03-06 16:14 UTC, bonjourmauko commented
poke @sylvainipp it looks like the problem you were having could come from inadvertently using a numpy > 2.2 version, that could be unrelated to your proposed changes in #1319

2025-03-07 10:52 UTC, merged